### ISSUE TITLE
how do I get a WoS username and password

### ISSUE THREAD

**Issue by GeraldCNelson** [vt-arc/wosr#10]
I realize this is not really your issue, but I was hoping you could point out where I have gone wrong. I have a username and password to `https://developer.clarivate.com/apis/wos` but when I enter that information into `auth()` it returns
`Error: No matches returned for Username gnelson@illinois.edu`

When I go to `https://developer.clarivate.com/users/me` I am told my email address is the one above and my external id is: 
`clarivate:9f84ea40-4837-11e9-93ff-b15400bdea2d`

I thought this might be my username but doesn't seem to be either.

**Comment by crew102** [comment]
Hi @GeraldCNelson , please see #8 for an answer to your question
