### ISSUE TITLE
clarivate transitioning WoS to json

### ISSUE THREAD

**Issue by GeraldCNelson** [vt-arc/wosr#11]
My librarian tells me that clarivate is transitioning access to the WoS database. It is switching (or has switched) from SOAP to json using an api key. Is this something that you are implementing or planning to implement in wosr?

**Comment by crew102** [comment]
Oh, interesting, I hadn't heard that. It does look like the API has changed recently, though. I don't currently have a valid set of credentials, so I won't be able to make the necessary changes to `wosr`.

**Comment by GeraldCNelson** [comment]
Does VT have a clarivate rep who is supposed to facilitate these things? Illinois is supposed to be (s)he has been remarkably unhelpful.

Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
Skype: jerrynelson
http://bit.ly/1arho7d

**Comment by crew102** [comment]
No, sorry.

**Comment by GeraldCNelson** [comment]
No valid credentials for the SOAP or json approach? If you still have SOAP credentials does wosr still work for you?

Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
Skype: jerrynelson
http://bit.ly/1arho7d

**Comment by crew102** [comment]
Both, I am no longer a subscriber to the API.

**Comment by GeraldCNelson** [comment]
Bummer! Is anyone taking over the development of wosr? Or is there an alternative that you know about?

Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
Skype: jerrynelson
http://bit.ly/1arho7d

**Comment by crew102** [comment]
No one is taking over that I know of. You can reach out to Clarivate and see if they know someone who can. My organization no longer has a license, though, so there's not much I can do.

**Comment by GeraldCNelson** [comment]
Do you have a contact at Clarivate that you could share?

Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
Skype: jerrynelson
http://bit.ly/1arho7d

**Comment by crew102** [comment]
I don’t, sry
