### ISSUE TITLE
use of WokSearchLite instead of WokSearch

### ISSUE THREAD

**Issue by GeraldCNelson** [vt-arc/wosr#13]
My university's SOAP access is through WokSearchLite instead of WoKSearch. This means several changes in query_wos. The body code needs to be something like

body <- paste0("<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\n    xmlns:woksearchlite=\"http://woksearchlite.v3.wokmws.thomsonreuters.com\">\n    <soapenv:Header/>\n    <soapenv:Body>\n    <woksearchlite:search>\n    <queryParameters>\n    <databaseId>WOS</databaseId>\n    <userQuery> ", 
                 escape_query(query), " </userQuery>", paste_eds_new(editions), 
                 "<queryLanguage>en</queryLanguage>\n    </queryParameters>\n    <retrieveParameters>\n    <firstRecord>1</firstRecord>\n    <count>0</count>\n    </retrieveParameters>\n    </woksearchlite:search>\n    </soapenv:Body>\n    </soapenv:Envelope>")
And the response code something like

response <- httr::POST("http://search.webofknowledge.com/esti/wokmws/ws/WokSearchLite", 
                         body = body, httr::add_headers(cookie = sprintf("SID=%s", 
                                                                         sid)), ua(), ...)
I can't figure out what the ua function is supposed to do.
ua <- function() httr::user_agent("https://github.com/vt-arc/wosr")

The help for user_agent says it is to override the default RCurl user agent of NULL, but that doesn't mean anything to me.

Finally, the structure of the search needs to be modified, in the paste_eds function.

I think the function below does the trick

paste_eds_new <- function(editions) {
  
  edition_vec <- sprintf(
    "<databaseId>%s</databaseId>", 
    editions)
  paste(edition_vec, collapse = " ")
}
These are a lot of changes and I'm still not having success with this code

**Comment by crew102** [comment]
The WokSearchLite API is different from the WokSearch API. `wosr` was designed to work with the WokSearch API and not the WokSearchLite API. It may not be trivial to edit the functions in `wosr` to get them to work with the SearchLite API.
