### ISSUE TITLE
Adding WOS query dictionary?

### ISSUE THREAD

**Issue by zrodriguez89** [vt-arc/wosr#17]
I looked through the provided links from the website and CRAN doc, and it was unclear the fields one can search and query (e.g. that PY is publication year), excluding the examples provided which show TS and PY.

Does there exist a document which lists and defines fields and shows formatting/example? Like:

PY- Publication Year. Format: ([Start Year]-[End Year])

**Comment by crew102** [comment]
I'm not sure where to find all of the official docs (b/c I don't have access to the WoS web app anymore, and that's where the docs were located back in the day). You can check out this: https://images.webofknowledge.com/images/help/WOS/hs_search_operators.html and this: https://researchguides.library.tufts.edu/c.php?g=249270&p=1660077. Hope that helps.

**Comment by zrodriguez89** [comment]
Thanks! The second link is definitely the most helpful. I still have a university subscription so if you point me to how to get the official docs, I would be willing to collect that kind of information if you would like.

**Comment by crew102** [comment]
Sorry, I don't have access to the site these days so I'm not sure where exactly to go. If you peruse the WoS web search app, there should be some links there to docs.
