### ISSUE TITLE
IP-Based Authentication Does Not Work as Described in Documentation

### ISSUE THREAD

**Issue by 414theodore** [vt-arc/wosr#6]
Calling the auth function as described in documentation to use IP-based authentication:

`auth(username = NULL, password = NULL)`

Causes the below error to appear:

Error in if (username == "" || password == "") { : 
  missing value where TRUE/FALSE needed

**Comment by 414theodore** [comment]
Thanks @crew102. Apologies, I'm relatively green to github and Im not sure how the commits work. At what point does a new build of the package get created that I can install the new version?

**Comment by crew102** [comment]
You can install the development version of the package (which contains the fix to your issue) by first installing `devtools` then using `install_github()`:

```r
if (!"devtools" %in% rownames(installed.packages())) 
  install.packages("devtools")

devtools::install_github("vt-arc/wosr")
```
