### ISSUE TITLE
Username authentication

### ISSUE THREAD

**Issue by Otoliths** [vt-arc/wosr#7]
Hi Chris Baker！
Error: User has no entitlement for this service level - WOKSearchPremiumen 
how to debug this error？

**Comment by crew102** [comment]
Hmm, I haven't seen that before. I just tried to authenticate using `auth()` and didn't have any problems. Have you been able to user `auth()` in the past?

**Comment by Otoliths** [comment]
Hi Chris Baker！
User auth() have been unavailable, the reason may be that the permissions of Web of Science are not enough.

**Comment by crew102** [comment]
Yeah, I suspect you're not using API credentials (perhaps you are using credentials for the WoS web app instead...these are different than API credentials). I'm going to close this issue for now, but feel free to reach out to me at chriscrewbaker@gmail.com if you have any more questions.
