### ISSUE TITLE
Error: No matches returned for Username

### ISSUE THREAD

**Issue by longhotuan** [vt-arc/wosr#8]
Hi,

Thank you very much for your great package! I have a problem of getting access to WoS as follows.

-When using the search with username and password  returns the following error: 'No matches returned for username'. The username is entered correctly, though.

-When using search without giving username/password (=NULL) I see the error : 'User has no entitlement for this service level - WOKSearchPremium'

Do you think it can be fixed? 

Many thanks for your time! 

Cheers

**Comment by crew102** [comment]
I just tried to authenticate using auth() and didn't have any problems. Have you two been able to user auth() in the past? Note that the API uses a different set of credentials than the WoS web app.

**Comment by longhotuan** [comment]
Yes. It seems that the website access and the API access are two separated products. I only have the website access while the API access is made via my institution.

**Comment by crew102** [comment]
Sorry, so you  have or have not been able to use auth() successfully in the past? If you haven't been able to, you likely are using website credentials instead of API credentials. If you're sure you're using the right set of credentials, then I'll look into this issue more.

**Comment by longhotuan** [comment]
No. It's ok. Many thanks! The thing is I don't have the API credentials. I have the access because my institution has to pay for the Web of Science Core Collection access. Nothing I can do about this.

**Comment by pederisager** [comment]
Hi Chris Baker,

I am fairly sure I have the same problem as @longhotuan (I have not been successfully able to use auth() in the past). Could you explain how I would go about acquiring API credentials?

**Comment by crew102** [comment]
You have to buy a subscription to the API from Clarivate Analytics. I don't know any specifics, as the company that I work for handled the purchasing.

**Comment by pederisager** [comment]
Ok, I will contact my university library then. Thanks for the input!

**Comment by elachtara** [comment]
Hi, 
Thank you for this discussion @pederisager.  I was curious as to whether buying the Clarviate API's fixed your connection issue? I had a similar issue to you. (auth() does not work for my account) 
Best,
Emily

**Comment by pederisager** [comment]
I never had any success acquiring API credentials from Clarivate. But if your institution has an IP-based API, the wosr usermanual specifies that you can set options `username=NULL` and `password=NULL`, and auth() will try to gain API access through the IP.

**Comment by RodBianc** [comment]
@pederisager do you know why if I use auth(username=NULL , password=NULL) and try the data <- pull_wos('TS = ("animal welfare") AND PY = (2002-2003)') a warning message comes: "Error: You need to provide a username and password to use the API"?

**Comment by pederisager** [comment]
@RodBianc sorry, I haven't got a clue.
